version: "3"
services:
    web:
      build: .
      environment:
        - MONGODB_CONNSTRING=mongodb://admin:password@mongodb:27017
      ports:
        - 3001:3000
      volumes:
        - ./:/app

    mongodb:
        image: mongo:latest
        restart: always
        environment:
          - MONGO_INITDB_ROOT_USERNAME=admin
          - MONGO_INITDB_ROOT_PASSWORD=password
        volumes:
          - mongodb_data:/data/db
        ports:
          - 27017:27017

    expresso:
        image: mongo-express:latest
        restart: always
        container_name: mongo-express
        depends_on:
          - mongodb
        ports:
          - 8081:8081
        environment:
          - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
          - ME_CONFIG_MONGODB_ADMINPASSWORD=password
          - ME_CONFIG_MONGODB_SERVER=mongodb

volumes:
  mongodb_data:
  